In [1]:
import numpy as np

In [2]:
X = np.random.randint(0,2,(75,20))

In [3]:
X

array([[1, 1, 1, ..., 0, 1, 1],
       [1, 1, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 0, 1],
       ...,
       [1, 1, 1, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 0, 1]])

In [4]:
#adding bias
X[:,-1]=1

In [5]:
X[:5,:]

array([[1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1]])

In [6]:
X.shape

(75, 20)

In [7]:
from sklearn.neural_network import MLPRegressor

In [8]:
mlp = MLPRegressor(solver='lbfgs',activation='logistic',learning_rate_init=0.00001, alpha=1e-5, 
                   hidden_layer_sizes=(10,5,10),max_iter=100000)

Train the network (fit)

In [9]:
mlp.fit(X,X)

MLPRegressor(activation='logistic', alpha=1e-05, hidden_layer_sizes=(10, 5, 10),
             learning_rate_init=1e-05, max_iter=100000, solver='lbfgs')

In [10]:
predictions = mlp.predict(X)
aa = (predictions > 0.5) ^ (X == 1)
np.count_nonzero(aa)

107

In [11]:
predictions[0]

array([ 0.53883   ,  1.39036301,  0.88777659,  0.55804219,  0.02216532,
        0.1921186 ,  1.34826241, -0.04261587,  0.55640103,  0.83103274,
        1.02265248,  0.76228543,  0.35641218,  0.67429989,  0.65262886,
        0.03279789,  0.0818741 ,  0.09902479,  0.95748843,  1.00002592])

In [12]:
1 ^ 0

1

In [13]:
predictions[0] > 0.5

array([ True,  True,  True,  True, False, False,  True, False,  True,
        True,  True,  True, False,  True,  True, False, False, False,
        True,  True])

In [14]:
X[0] == 1

array([ True,  True,  True,  True, False, False,  True, False,  True,
        True,  True,  True, False,  True,  True, False, False, False,
        True,  True])

In [15]:
predictions

array([[ 0.53883   ,  1.39036301,  0.88777659, ...,  0.09902479,
         0.95748843,  1.00002592],
       [ 0.35519728,  0.83730136,  0.2416612 , ...,  0.72609795,
         1.03159039,  1.00002528],
       [ 0.90984573, -0.00772783,  0.1666765 , ...,  1.09067438,
         0.4386984 ,  0.9999879 ],
       ...,
       [ 0.75297611,  0.56612434,  1.15162093, ..., -0.09381271,
         0.83071334,  1.00001304],
       [ 1.24476457,  1.18245743,  1.19433421, ...,  0.2669463 ,
         1.13498284,  1.00000862],
       [ 0.93713271,  0.20450575,  0.15346941, ...,  0.93444714,
         0.19760828,  0.99999553]])

In [16]:
aa.shape

(75, 20)

In [17]:
print(len(mlp.coefs_))
for i in mlp.coefs_:
    print (i.shape)

4
(20, 10)
(10, 5)
(5, 10)
(10, 20)


In [18]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

# Encode

In [19]:
samp = X[0]

In [20]:
samp

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [21]:
l1 = sigmoid(np.dot(samp,mlp.coefs_[0])+mlp.intercepts_[0])
l2 = sigmoid(np.dot(l1,mlp.coefs_[1])+mlp.intercepts_[1])
print(l2)

[0.8356152  0.21739453 0.93152255 0.48451775 0.92357628]


# Decode

In [22]:
l3 = sigmoid(np.dot(l2,mlp.coefs_[2])+mlp.intercepts_[2])
l4 = np.dot(l3,mlp.coefs_[3])+mlp.intercepts_[3]
res = np.abs(np.round(l4,0))
res.astype(np.int)

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1])